name: Notify Slack on Pull Request Events

on:
  pull_request:
    types: [opened, closed, edited, reopened, synchronize]

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Send notification to Slack and add reaction
        if: github.event.action == 'opened'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          response=$(curl -s -o response.json -w "%{http_code}" -X POST -H 'Content-type: application/json' --data '{
            "text": "[${{ github.actor }}]: ${{ github.event.pull_request.html_url}} - ${{ github.event.pull_request.title }}"
          }' $SLACK_WEBHOOK_URL)
          if [ "$response" -ne 200 ]; then
            echo "Error sending notification to Slack"
            cat response.json
            exit 1
          fi
          response_content=$(cat response.json)
          timestamp=$(echo $response_content | jq -r '.ts')
          if [ -z "$timestamp" ]; then
            echo "Error: No timestamp found in Slack response"
            exit 1
          fi
          echo "SLACK_MESSAGE_TIMESTAMP=$timestamp" >> $GITHUB_ENV

          REACTION="white_check_mark"
          reaction_response=$(curl -s -o reaction_response.json -w "%{http_code}" -X POST -H "Authorization: Bearer $SLACK_BOT_TOKEN" -H "Content-type: application/json" --data '{
            "channel": "your-slack-channel",
            "name": "'$REACTION'",
            "timestamp": "'$timestamp'"
          }' https://slack.com/api/reactions.add)
          if [ "$reaction_response" -ne 200 ]; then
            echo "Error adding reaction to Slack message"
            cat reaction_response.json
            exit 1
          fi