name: Notify Slack on Pull Request Events

on:
  pull_request:
    types: [opened, closed, edited, reopened, synchronize]

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Send notification to Slack (or Add Reaction)
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          ACTION=${{ github.event.action }}
          TITLE="${{ github.event.pull_request.title }}"
          URL="${{ github.event.pull_request.html_url }}"
          ACTOR="${{ github.actor }}"

          # Define a reaction emoji based on the action
          if [ "$ACTION" == "opened" ]; then
            EMOJI="eyes"
          elif [ "$ACTION" == "closed" ]; then
            EMOJI="white_check_mark"
          elif [ "$ACTION" == "reopened" ]; then
            EMOJI="arrows_clockwise"
          elif [ "$ACTION" == "edited" ]; then
            EMOJI="pencil2"
          elif [ "$ACTION" == "synchronize" ]; then
            EMOJI="repeat"
          fi

          # Install jq
          sudo apt-get update && sudo apt-get install -y jq

          # Load timestamp
          TIMESTAMP_FILE=".slack_timestamp"
          if [ -f "$TIMESTAMP_FILE" ]; then
            TIMESTAMP=$(cat "$TIMESTAMP_FILE")
          fi

          # If the PR is opened, send a new message and save its timestamp
          if [ "$ACTION" == "opened" ]; then
            RESPONSE=$(curl -s -X POST -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
              -H 'Content-type: application/json' \
              --data '{
                "channel": "C084G0DQXBL", # Use o ID do canal aqui
                "text": "Pull Request Opened: *'"$TITLE"'*\nBy: '"$ACTOR"'\nURL: '"$URL"'"
              }' https://slack.com/api/chat.postMessage)
            echo "$RESPONSE" | jq -r '.ts' > "$TIMESTAMP_FILE"
          else
            if [ ! -z "$TIMESTAMP" ]; then
              curl -s -X POST -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
                -H 'Content-type: application/json' \
                --data '{
                  "channel": "C084G0DQXBL", # Use o ID do canal aqui
                  "timestamp": "'"$TIMESTAMP"'",
                  "name": "'"$EMOJI"'"
                }' https://slack.com/api/reactions.add
            fi
          fi
